---
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(readxl)
```

# Power analysis of Poisson Regression with Bernoulli Distribution

Power analysis are essential in the design of study. G-power, PASS and WebPower from R packages are three main software to compute power, sample size and effect size. In this study, we focus on the power analysis of Poisson Regression with Bernoulli Distribution. We find there is a slightly difference for Poisson regression among the results from these software. We plan to discuss and find the reason of the difference, and give suggestions to power analysis for Poisson regression. This could help to understand the pros and cons of these software, and be careful to select software.   

In order to more intuitively show the running results of different software，we also use the Shinny APP to create an interactive interface for power analysis. The App could display power analysis by different software. With different parameter for each type of power analysis, we could get a table and plot based on results from different software.   


## Study defination  
The outcome variable Y is a discrete count variable, which assumes to follow poisson distribution. The probability of y with parameter of poisson distribution "$\lambda$" and during the exposure time "t" is,    

$$P(Y=y|\lambda,t)=\frac{e^{-\lambda t}(\lambda t)^{y}}{y!}$$

A sample poisson regression with only one covariate of Bernoulli distribution is,  

$$log(\lambda)=b_0+b_1X$$

The definitions of R Shiny inputs as below:

Type of power analysis: Power, Sample Size, Effect Size   

Alternative: two sided or one side   

expb0: the mean event rate assumed under $H_0$  

expb1: the relative increase of the event rate over the mean rate assumed under $H_0$   

Mean exposure: the time unit during which the events are counted   

Parameter of Bernoulli distribution: the probability of Bernoulli distribution when X=1   

Type I error: the probability that the test falsely rejects the null hypothesis

Sample size: the smallest sample size for designed power

Increment: set for sample size or power    

Power: the probability that the test correctly rejects the null hypothesis

Simulation times:set for Mente-Carlo simulation


## Methods for different software 

Based on the large sample approximation procedure for logistic regression by Whittemore(1982), Signorini(1991) gave a general approach to calculate power for poisson regression with one covariate. This method considers $\beta_1$ as the parameter of interest, and uses Wald test $Z=\frac{\hat b_1}{Var(\hat b_1)}$. For a two sides hypothesis, $H_0: b_1=0 \  vs. H_1: b_1\neq0$ at the significant of $\alpha$ and with the power of $1-\beta$, assuming N is large enough to apply the asymptotic results, the fomular given by Signorini(1991) is,

$$N=\frac{\bigg(z_{1-\alpha/2}\sqrt{var(\hat 
b1|H_0)}+z_{1-\beta}\sqrt{var(\hat b1|H_1)} \bigg)^2}{tb1^2}$$
For Bernoulli distribution,
$$var(\hat \beta_1|H_0)=\frac{1}{p*(1-p)*expb0}$$
$$var(\hat \beta_1|H_1)=\frac{1}{(1-p)*expb0}+\frac{1}{p*expb1*expb0}$$

PASS uses this method. From the formula, we could derive power or sample size or effect size if we inputs two of them and other inputs expb0,t,p,$\alpha$. 

Demidenko(2007) gave a general formula for sample size of logistic regression, and noted that Whittemore(1982) does not entirely reflect the way Wald tests are used in practice. Specifically, the formula from Signorini(1991) is not accurate since the null hypothesis is the unknown parameter takes value of 0, assuming $\beta=0$. Demidenko shows the test statistics is $Z=\frac{\sqrt{n}(\hat \beta_1-0)}{\sqrt{\hat V}}$, $V$ is the variance of $\sqrt{n}(\hat \beta_1)$ under the alternative hypothesis $H_1: \beta_1 \neq0$. So the formula for poisson regression is,

$$N=\frac{\big(z_{1-\alpha/2}+z_{1-\beta}\big)^2V}{tb1^2}$$
For Bernoulli distribution,
$$V=\frac{1}{(1-p)*expb0}+\frac{1}{p*expb0*expb1}$$

Webpower from R package uses this method. And it only works out for power and sample size. In this study, we also computed the effect size of this method. 

Demidenko(2007) also shows in skewed X distribution, a variance correction can be selected to compensate the variance distortions. G-power combines the formula from Signorini(1991) and Demidenko(2007) with variance correction. With correction, the variance under $H_0$, choose $\beta_1=0, \beta_0=b0^*, expb0^*=\int f(x)exp(\beta_0+\beta_1x)dx$The formula for poisson regression is, 

$$N=\frac{\bigg(z_{1-\alpha/2}\sqrt{var(\hat 
b1|H_0^*)}+z_{1-\beta}\sqrt{var(\hat b1|H_1)} \bigg)^2}{tb1^2}$$
For Bernoulli distribution,
$$expb0^*=\int f(x)exp(b0+b1x)dx=p*expb0*expb1+(1-p)*expb0$$

$$var(\hat \beta_1|H_0^*)=\frac{1}{p*(1-p)*expb0^*}$$
$$var(\hat \beta_1|H_1)=\frac{1}{(1-p)*expb0}+\frac{1}{p*expb1*expb0}$$

Besides the methods above, we also develop Monte Carlo simulation to estimate power of poisson regression. Based on generate random data with specified sample size and parameter of distribution, we use R command "glm" on those randomly generated data and obtain the p-value for the test. We reject the null hypothesis when the p-value is less than our significance level. we repeat these steps for n times. Our estimate of power is the proportion of times that the null hypothesis is rejected. 


## Discussion 
Comparing simulation and different software results of Poisson Regression with Bernoulli Distribution, We found the results from G-power and Webpower is very colse, and G-power is more accurate to power calculation. The results from PASS is the most inaccurate and should be used carefully. We created Shiny App to display the results and it could help to do power analysis when designing the study. 

